spring:
  profiles:
    active: default
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: mongodb://localhost:27017/pet-care
  mail:
    verificationUrl: http://localhost:8080/users/verify/account/
    resendVerificationUrl: http://localhost:8080/users/verify/account/resend/email/
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: TestController
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
server:
  port: 8080
admin:
  email: admin@app.com
  password: appAdmin2018
